import type { Metadata } from 'next';
import './globals.css';
import { Noto_Sans } from 'next/font/google';
import { Title } from '../components/title/title';
import { Sidebar } from '../components/sidebar/sidebar';
import styles from './layout.module.css';

const notoSans = Noto_Sans({
  display: 'swap',
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: 'Owl top',
  description: 'Generated by create next app',
  keywords: ['template', 'main page'],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang='en'>
      <body className={`${notoSans.className}`}>
        <div className={styles.container}>
          <div className={styles.containerSidebar}>
            <Title></Title>
            <Sidebar></Sidebar>
          </div>
          <main className={styles.containerMain}>{children}</main>
        </div>
      </body>
    </html>
  );
}
